//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkCupidAutoBot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class OkSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static OkSettings defaultInstance = ((OkSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OkSettings())));
        
        public static OkSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("username")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string password {
            get {
                return ((string)(this["password"]));
            }
            set {
                this["password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int matchThreshhold {
            get {
                return ((int)(this["matchThreshhold"]));
            }
            set {
                this["matchThreshhold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NYC1AGLMKNGUYE1;Initial Catalog=OKCUPIDDB01;Integrated Security=True")]
        public string sqlConnection {
            get {
                return ((string)(this["sqlConnection"]));
            }
            set {
                this["sqlConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProfileId,Username,Age,Location,Percentage,Enemy,LastOnline,Orientation,Ethnicity" +
            ",Height,BodyType,Diet,Smokes,Drinks,Drugs,Religion,Sign,Education,Job,Income,Rel" +
            "ationshipStatus,RelationshipType,Offspring,Pets,Speaks,CreatedBy,CreatedDt")]
        public string profileFields {
            get {
                return ((string)(this["profileFields"]));
            }
            set {
                this["profileFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProfileId,essay0,essay1,essay2,essay3,essay4,essay5,essay6,essay7,essay8,what_i_w" +
            "ant,essay9,CreatedBy,CreatedDt")]
        public string essayFields {
            get {
                return ((string)(this["essayFields"]));
            }
            set {
                this["essayFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int sqlOrExcel {
            get {
                return ((int)(this["sqlOrExcel"]));
            }
            set {
                this["sqlOrExcel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[DimProfile]")]
        public string detailsTable {
            get {
                return ((string)(this["detailsTable"]));
            }
            set {
                this["detailsTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[dbo].[FactEssay]")]
        public string essaysTable {
            get {
                return ((string)(this["essaysTable"]));
            }
            set {
                this["essaysTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("girls.xlsx")]
        public string excelFile {
            get {
                return ((string)(this["excelFile"]));
            }
            set {
                this["excelFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.okcupid.com")]
        public string baseUri {
            get {
                return ((string)(this["baseUri"]));
            }
            set {
                this["baseUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int girlsPerSession {
            get {
                return ((int)(this["girlsPerSession"]));
            }
            set {
                this["girlsPerSession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/match?timekey=1&matchOrderBy=SPECIAL_BLEND&use_prefs=1&discard_prefs=1&count=50")]
        public string matchesQueryString {
            get {
                return ((string)(this["matchesQueryString"]));
            }
            set {
                this["matchesQueryString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool callThrottling {
            get {
                return ((bool)(this["callThrottling"]));
            }
            set {
                this["callThrottling"] = value;
            }
        }
    }
}
